---
title: "Instalaciones"
description: "Instalación de software para el curso Biodata en Linux"
output:
  distill::distill_article:
    toc: true
    toc_float: true
    pandoc_args: ["--number-sections"]
---

Según la distribución de linux, los procesos de instalación son muy diferentes.

En este documento voy a enfocarme en los paquetes de Ubuntu y Linux Mint con el gestor de paquetes *apt*, considerando que son las distribuciones por las cuales los usuarios usualmente empiezan en el mundo Linux. Si necesitan ayuda para instalar paquetes en otras distribuciones, no duden en contactarme.

Este documento funciona con las ultimas versiones "LTS" de ubuntu (Jammy Jellyfish) y las versiones 21 de Linux Mint.
Si tienen otra versión, el principio es el mismo y la mayoría de los comandos de apt funcionan igual, excepto los comandos que se refieren directamente a "Jammy" o `lsb_release`.


# R

Voy a reproducir los comandos acá, si quieren entender mejor el proceso, referirse a <https://cran.r-project.org/bin/linux/ubuntu/> o <https://es.linux-console.net/?p=14068>.


Existe un repositorio dedicado a los paquetes del CRAN (que maneja R y los paquetes de R) para apt.

Prerequisitos:

```bash
sudo apt update
sudo apt install software-properties-common dirmngr -y
```




Añadir el CRAN como repositorio de paquetes para apt:

**En ubuntu** *(notar, eso funciona con todas las versiones LTS)*:

```bash
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
```

**En Linux Mint 21** *(potencialmente puede ser una solución, aunque imperfecta, en las versiones de ubuntu que no son LTS)*:

```bash
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/"
```


Hay un proceso de seguridad que necesita integrar llaves en el sistema apt:

```bash
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
```

Ahora pueden instalar R:

```bash
sudo apt update
sudo apt install r-base r-base-dev -y
```



# Rstudio

RStudio no está en los repositorios apt para ubuntu, tienen que descargarlo y instalarlo:

**Para Linux Mint 21 y Ubuntu 22.04 Jammy Jellyfish**:

```bash
wget https://download1.rstudio.org/electron/jammy/amd64/rstudio-2023.09.1-494-amd64.deb
sudo apt install ./rstudio-2023.09.1-494-amd64.deb
```

Para otras versiones, mirar: <https://posit.co/download/rstudio-desktop/>


# PostgreSQL, postgis, SQLite y spatialite

Para instalar todos los paquetes SQL que vamos a necesitar (eso es valido el 1 de noviembre de 2022):

```bash
sudo apt install postgresql postgresql-contrib postgis postgresql-14-postgis-3 sqlite3 libsqlite3-mod-spatialite -y
```

# Interfaces para SQL

Vamos a utilizar DBeaver.
Como para R, tenemos que instalar un repositorio particular para DBeaver:

```bash
curl -fsSL https://dbeaver.io/debs/dbeaver.gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/dbeaver.gpg
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
sudo apt update
sudo apt install dbeaver-ce -y
```

Si quieren, pueden instalar una interfaz especifica para PostgreSQL:

```bash
sudo apt install pgAdmin4
```

# QGIS

Existen soluciones para instalar las ultimas versiones de QGIS (ver <https://www.qgis.org/en/site/forusers/alldownloads.html>), pero la versión en los repositorio por defecto es suficiente para el curso:

```bash
sudo apt install qgis python3-qgis
```

